#!/usr/bin/env dotnet-script
#r "nuget: TableAPI, 1.0.4.1"

// This script generates a SQL script to create and populate a table for house price analysis data.
// It ensures the net_sqm column is rounded to 1 decimal place for consistency.
// The generated SQL script includes CREATE TABLE and INSERT statements.

using Squirrel;
using System.IO;
using System.Linq;
using System.Globalization;

// Load the processed CSV file
var data = DataAcquisition.LoadCsv("house-price-per-sqm.csv");

// Use Squirrel's AddColumn with LINQ to round net_sqm (1 decimal place)
// This leverages the library's LINQ integration and avoids formula parsing issues
var roundedSqm = data["net_sqm"]
    .Select(x => decimal.Parse(x, CultureInfo.InvariantCulture))
    .Select(x => Math.Round(x, 1).ToString(CultureInfo.InvariantCulture))
    .ToList();

data.AddColumn("net_sqm_rounded", roundedSqm);

// Project to a new table structure to rename the column back to 'net_sqm'
// We use Enumerable.Range because Table might not implement IEnumerable<Row> directly
var cleanedData = Enumerable.Range(0, data.RowCount)
    .Select(i => data[i])
    .Select(row => new 
    {
        bedroom_count = row["bedroom_count"],
        net_sqm = row["net_sqm_rounded"], // Map rounded value to original name
        center_distance = row["center_distance"],
        metro_distance = row["metro_distance"],
        floor = row["floor"],
        age = row["age"],
        price = row["price"],
        price_per_sqm = row["price_per_sqm"]
    })
    .ToTableFromAnonList();

cleanedData.Name = "HousePriceAnalysis";

// Define a record type to map the CSV columns to strongly typed properties
// This helps Squirrel infer the correct SQL data types
record HousePriceData(
    int bedroom_count, 
    decimal net_sqm, 
    decimal center_distance, 
    decimal metro_distance, 
    int floor, 
    int age, 
    decimal price, 
    decimal price_per_sqm
);

// Convert the generic Table to a strongly-typed RecordTable
var recordTable = RecordTable<HousePriceData>.FromTable(cleanedData);

// Convert to a SQL Table representation
var sqlTable = recordTable.ToSqlTable();

// Generate the CREATE TABLE script
var createTableScript = sqlTable.CreateTableScript;

// Generate the INSERT statements
var insertScripts = sqlTable.RowInsertCommands;

// Combine them into a single SQL script
var fullSqlScript = $"-- Generated by Squirrel Data Analysis on {DateTime.Now}\n\n";
fullSqlScript += "-- 1. Create the table\n";
fullSqlScript += createTableScript + ";\n\n";
fullSqlScript += "-- 2. Insert data\n";
fullSqlScript += string.Join("\n", insertScripts);

// Write the SQL script to a file
string outputFileName = "house-price-sql-loader.sql";
File.WriteAllText(outputFileName, fullSqlScript);

Console.WriteLine($"Successfully generated SQL script: {outputFileName}");
Console.WriteLine($"Total rows to insert: {insertScripts.Count}");
